%YAML:1.0
image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ 602.50925,    0.     ,  671.40588,
            0.     ,  607.33119,  333.29582,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients: !!opencv-matrix
  rows: 1
  cols: 5
  dt: d
  data: [-0.240418, 0.043584, -0.001764, -0.000712, 0.000000]
rectification_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix: !!opencv-matrix
  rows: 3
  cols: 4
  dt: d
  data: [ 414.04932,    0.     ,  663.95814,    0.     ,
            0.     ,  547.00494,  325.21805,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
